version: "3"

services:
  php:
    build: .
    depends_on:
      - mysql
    command: migrate
    volumes:
      - .:/var/www/html
    networks: 
      - hubdesk
    ports:
      - 3000:3000

  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    networks: 
      - hubdesk
    environment: 
      MYSQL_ROOT_PASSWORD: "hubdeskroot"
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

networks: 
  hubdesk:
  
volumes: 
  mysql-data:

    